In [43]:
import numpy as np

In [44]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [45]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [46]:
def sigmoid(x):
  return i/(1+np.exp(-x))

In [47]:
def derivative_sigmoid(x):
  return x*(1-x)

In [48]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [49]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [50]:
wh

array([[0.4617949 , 0.01113738, 0.16985333],
       [0.92344863, 0.46657375, 0.92062675],
       [0.92445549, 0.64401767, 0.75679807],
       [0.69704001, 0.22979968, 0.61030741]])

In [51]:
wo

array([[0.23955329],
       [0.70863107],
       [0.96324426]])

In [52]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr

<ipython-input-46-248f26f30fa2>:2: RuntimeWarning: overflow encountered in exp
  return i/(1+np.exp(-x))


In [53]:
output

array([[2499.5],
       [2499.5],
       [2499.5]])